name: smsapi
description: "SMS MyBot"
publish_to: 'none'

version: 1.0.5+105

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  background_sms: ^0.0.4
  http: ^1.2.1
  cron: ^0.6.0
  get: ^4.6.6
  get_storage: ^2.1.1
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png" 

flutter:

  uses-material-design: true
